### PR TITLE
💄Change StudyNavBar Logs button to Events

### LINKED ISSUE #1094: Rename study Logs tab to Events
**Sender**: natasha@d3b.center
**Comment**: Can we rename Logs to Events? This would be more relevant to what's being displayed and also would be more consistent with the Admin Events view
[Open #141 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/141)
**Notes**:
 - (1) Can we rename to Events? This would be more relevant to what's being displayed and also would be more consistent with the Admin Events view

<a href='https://usersnappublic.s3.amazonaws.com/2021-08-23/20-00/ba44dd89-67e7-415c-b791-5fec00631536.png'>⚠️ - Rename study Logs tab to Events</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-08-23/20-00/ba44dd89-67e7-415c-b791-5fec00631536.png'>Download original image</a>

**Browser**: Chrome 92 (Macintosh)
**Referer**: [https://data-tracker.kidsfirstdrc.org/study/SD_CZEV905M/logs](https://data-tracker.kidsfirstdrc.org/study/SD_CZEV905M/logs)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 821

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

### PR DESCRIPTION
**Pull request by gsantia**
Closes #1094 . Changes the StudyNavBar Logs button to say Events and updates the route name from `logs` to `events`.

## Visual Changes

Screen Shot 2021-09-17 at 1 20 46 PM

This button used to say Logs

### CODE REVIEW

**Comment by znatty22** [comment]
@gsantia The integration tests have been failing for a while so you don't have to worry about those. But you can get unit tests to pass by updating the snapshots. See https://github.com/kids-first/kf-ui-data-tracker#unit-tests

File: src/components/StudyNavBar/StudyNavBar.js [hunk 1]
```diff
@@ -34,8 +34,8 @@ const StudyNavBar = ({match, history, isBeta}) => {
       endString: 'collaborators',
     },
     {
-      tab: 'Logs',
-      endString: 'logs',
+      tab: 'Events',
+      endString: 'events',
```
Comment (dankolbman) [inline src/components/StudyNavBar/StudyNavBar.js:38]: If you're going to change this, you need to update the route, too. I think you're safe just keeping it as `events` as it only shows up in the url.

Comment (gsantia) [reply src/components/StudyNavBar/StudyNavBar.js:38]: i did in another commit

**Review by znatty22 — APPROVED** [review]
Looks ok to me but I'd like this to have Xu/Dan's approval too

**Review by XuTheBunny — APPROVED** [review]
