### PR TITLE
🐛 Fix study table sorting error on expected samples column

### LINKED ISSUE #777: Blank screen after sorting on number of expected samples
**Sender**: taylordm@email.chop.edu
**Comment**: Sorted on expected # of studies and page crashed/went blank.
[Open #18 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/18)

<a href='https://usersnappublic.s3.amazonaws.com/2020-06-25/14-33/4b30cf52-51d6-4667-a01a-a8252f95cc23.png'>⚠️ - blank screen after sorting on number of expected samples</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-06-25/14-33/4b30cf52-51d6-4667-a01a-a8252f95cc23.png'>Download original image</a>

**Browser**: Firefox 77 (macOS Mojave)
**Referer**: [https://kf-ui-data-tracker.kidsfirstdrc.org/](https://kf-ui-data-tracker.kidsfirstdrc.org/)
**Screen size**: 1824 x 1140 **Browser size**: 1531 x 807

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

### PR DESCRIPTION
**Pull request by XuTheBunny**
image

Closes #777

### CODE REVIEW

File: src/components/StudyList/StudyTable.js [hunk 1]
```diff
@@ -63,6 +63,7 @@ const renderRow = (node, columns) => ({
 
 const stringSort = (a, b) =>
   a !== null && b !== null ? a.localeCompare(b) : 0;
+const intSort = (a, b) => a !== null && b !== null && a < b;
```
Comment (dankolbman) [inline src/components/StudyList/StudyTable.js:66]: I think this needs to be flipped to `b > a`
