### PR TITLE
✨ Add UI version number banner to footer

### LINKED ISSUE #490: Add UI version number into ui
To help visually keep track of what version the ui is bug reports like UserSnap and usability test it woudl be great to add the semver into the UI, maybe as small text at the bottom or in the header under `Data Tracker`
Screen Shot 2019-09-24 at 2 04 56 PM

### PR DESCRIPTION
**Pull request by XuTheBunny**
## Feature or Improvement

- Add UI version number and commit hash banner to footer
- Will add `Study Creator API` version later
- Have different look on production, development and local

## UI changes

**Before:**
image

**After:**
Local:
Screen Shot 2019-11-06 at 10 50 46 AM
Development:
Screen Shot 2019-11-06 at 10 51 12 AM
QA:
image
Production:
Screen Shot 2019-11-06 at 10 51 19 AM

## Browsers Tested

| Browser             | 1024px | 768px | 480px | 320px |
| ------------------- | :----: | ----: | ----: | ----: |
| Chrome (77)  | ✅ | ✅ | ✅ | ✅ |
| Firefox (69) | ✅ | ✅ | ✅ | ✅ |
| Safari (12)  | ✅ | ✅ | ✅ | ✅ |
| IE (11)      |  ✖️   |   ✖️     |  ✖️      |    ✖️    |

Closes #490

### CODE REVIEW

File: src/components/Header/Header.js [hunk 1]
```diff
@@ -15,71 +24,123 @@ const Header = ({data: {loading, error, myProfile: profile}}) => {
...
-          </>
-        )}
-      </Container>
-    </Menu>
+              </Menu.Menu>
+            </>
+          )}
+        </Container>
+      </Menu>
+      <Segment vertical basic className="footer">
```
Comment (bdolly) [inline src/components/Header/Header.js]: the footer needs moved to its own component and not be part of the header component

File: src/components/Footer/Footer.js [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+          <Label
+            className="text-10"
+            basic
+            horizontal
+            color={colors[syslevel] || 'red'}
+          >
+            {syslevel}
+          </Label>
+        )}
+        v{' '}
```
Comment (dankolbman) [inline src/components/Footer/Footer.js]: Can you remove the `v` since it's not part of our versioning scheme?

File: src/App.css [hunk 3]
```diff
@@ -177,3 +177,20 @@ body {
...
   }
 }
+
+.footer {
+  background: white !important;
+  padding: 9px 0px !important;
+  position: fixed !important;
+  left: 0;
+  bottom: 0;
+  width: 100%;
```
Comment (bdolly) [inline src/App.css]: for safety might want to throw a `z-index` on this with a pretty high value, this way we guarantee it stays on the top layer

File: src/Routes/index.js [hunk 4]
```diff
@@ -32,21 +33,34 @@ const Routes = () => (
...
-      <AdminRoute exact path="/tokens" component={TokensListView} />
-      <AdminRoute
-        exact
-        path="/cavatica-projects"
-        component={CavaticaProjectsView}
-      />
-      <AdminRoute exact path="/events" component={EventsView} />
-      <DocumentRoutes />
-    </Switch>
+    <div className="page">
```
Comment (bdolly) [inline src/Routes/index.js]: looks like `ProfileView` and `NewStudyView` ☝️ would be left out of the wrapper?

File: src/components/Footer/Footer.js [hunk 5]
```diff
@@ -0,0 +1,62 @@
+import React from 'react';
+import {Container, Segment, Label, List} from 'semantic-ui-react';
+
+const Footer = () => {
+  const lastVersion = process.env.REACT_APP_LAST_VERSION;
+  const colors = {
```
Comment (bdolly) [inline src/components/Footer/Footer.js]: grrrr semantic and it's lack of utility classes

File: src/components/Footer/Footer.js [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+                basic
+                horizontal
+                color={colors[syslevel]}
+              >
+                {syslevel}
+              </Label>
+            </List.Item>
+          )}
+          <List.Item className="noMargin">
+            Data Tracker UI{' '}
```
Comment (bdolly) [inline src/components/Footer/Footer.js]: let's just make this `UI`, the header let's us know we're in the Data Tracker

File: src/App.css [hunk 7]
```diff
@@ -177,3 +177,24 @@ body {
...
+  z-index: 1000;
+  border-radius: 0px !important;
```
Comment (bdolly) [inline src/App.css]: Semantic make me 😢 as a front-end dev

File: src/components/Footer/Footer.js [hunk 8]
```diff
@@ -0,0 +1,59 @@
+import React from 'react';
+import {Container, Segment, Label, List} from 'semantic-ui-react';
+import {systemEnvColors} from '../../common/enums';
+
+const Footer = () => {
+  const lastVersion = process.env.REACT_APP_LAST_VERSION;
+
+  var syslevel = 'local';
```
Comment (dankolbman) [inline src/components/Footer/Footer.js]: Can we make sure to include qa, too? It may be easiest to just include another environment variable for syslevel, but you could probably also figure it out based on the git vars.

File: src/common/enums.js [hunk 9]
```diff
@@ -168,3 +168,11 @@ export const versionState = {
   PRC: {title: 'Processed', labelColor: 'blue'},
   UPD: {title: 'Updated', labelColor: 'blue'},
 };
+
+// Store label colors for system version footer
+export const systemEnvColors = {
+  local: 'orange',
+  development: 'yellow',
```
Comment (dankolbman) [inline src/common/enums.js]: should be `dev`
