### PR TITLE
✨ Add multi-selection for tag filter with untagged option

### LINKED ISSUE #820: Tag filters match wrong tags (partial substrings)
**Sender**: avikelman@d3b.center
**Comment**: If a tag is a substring of another tag, filtering for the first tag doesn't remove the other tag.
[Open #42 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/42)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-31/17-06/6cc32afa-5de1-4973-8b68-0a4ae0d2276a.png'>⚠️ - Tag filters match wrong tags (partial substrings)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-31/17-06/6cc32afa-5de1-4973-8b68-0a4ae0d2276a.png'>Download original image</a>

**Browser**: Safari 13 (macOS Mojave)
**Referer**: [https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents](https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

### LINKED ISSUE #821: Enable selection of multiple simultaneous tag filters
## Feature Justification

It's not currently possible to filter for the intersection of multiple tags. For why this is important, see: https://www.notion.so/d3b/Tags-vs-Folders-b7f00d9ee21f45d581737163da2dc004

## Proposed Change or Addition

A way to select more than one tag filter at once.

Subsequent choices should be limited to ones that intersect with the current choices.

### LINKED ISSUE #823: Add a filter for showing only untagged files.
## Feature Justification

Tags are the ideal way to organize data into sets, but the final set is the untagged set, and that is not currently represented in the filters.

## Proposed Change or Addition

The tag filtering mechanism should have a filter option for showing only untagged files.

### PR DESCRIPTION
**Pull request by XuTheBunny**
✨ Add tag filter option for untagged files
image

✨ Add multi-selection for tag filter with intersect or union option
image

Closes #820 
Closes #821 
Closes #823

### CODE REVIEW

File: src/documents/views/StudyFilesListView.js [hunk 1]
```diff
@@ -52,9 +52,16 @@ const filterFiles = (fileList, filters) => {
     obj.node.fileType.includes(filters.typeFilterStatus),
   );
   // Filter by tags
-  filteredList = filteredList.filter(obj =>
-    obj.node.tags.join(',').includes(filters.tagFilterStatus),
-  );
+  if (filters.tagFilterStatus.length > 0) {
+    filteredList = filteredList.filter(obj =>
+      filters.tagFilterStatus.includes('untagged')
```
Comment (dankolbman) [inline src/documents/views/StudyFilesListView.js:57]: I suppose you just need to acknowledge that the user may make a tag of their own called `untagged` and may then get back those tags if they choose the `-- untagged --` filter.

**Comment by fiendish** [comment]
Looks good except for one thing. The untagged filter creates invalid results. For instance:
Screen Shot 2020-08-04 at 12 58 12 PM

File: src/documents/views/StudyFilesListView.js (hunk 1 above)
Comment (fiendish) [reply src/documents/views/StudyFilesListView.js:57]: Maybe don't allow creating their own tag called "untagged".
