### PR TITLE
✨ Remove file upload/edit block from document title validation

### LINKED ISSUE #520: Cannot upload a new document when there is no documents exist from Safari
## UI Version

semantic-ui-react - 0.87.1

## URL

It can be any study that doesn't have documents.
http://localhost:3000/study/SD_745WVV0R/documents

## ScreenShot(s)
**Only happens on Safari**
Screen Shot 2019-10-17 at 12 14 54 PM
Screen Shot 2019-10-17 at 12 15 16 PM

## Steps To Reproduce

Go to any study that doesn't have any documents and try to add a new document

## Expected Behavior

When clicking on the upload button, expect the button change to "UPLOADING..." stage

## Observed Behavior

Nothing changed on the page, the update button is active but not change to "UPLOADING..." stage
There is no GraphQL sent out on clicking the upload button

### LINKED ISSUE #521: Cannot save edited document title
## UI Version
Version 0.8.1

## URL
https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_46SK55A3/documents/SF_0Q9WAXVQ

## ScreenShot(s)
image

## Steps To Reproduce

1. Clicked edit button
2. Modified document title from `s3-harmonized-gf-manifest` to `s3-harmonized-gf-manifest-fy15`
3. Clicked save button

## Expected Behavior

Modified title persists

## Observed Behavior

Nothing happened after clicking save button on edit modal. The modal stayed up. Tried refreshing page to see if the update was applied anyway but the title wasn't changed

### LINKED ISSUE #529: Unable to upload even when study document title and file name are reasonably different
## UI Version

0.8.1

## URL

https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_46SK55A3/documents/new-document

## ScreenShot(s)

Provide a screenshot(s) to quickly evaluate the visual aspect of the issue
image

## Steps To Reproduce

Click Upload document > Click Create New Document

## Expected Behavior

1. I think data tracker should NOT prevent upload based on how similar the file name and study document names are. The file name might be sufficiently descriptive and the uploader may want to use it for the title of the study document

2. My title seemed different enough, but I am still prevented from uploading. Seems like a bug 

## Observed Behavior

Couldn't upload file and create a new study document

### LINKED ISSUE #535: Remove document name validation
We should remove any hard constraints on file upload based on either the file name or the document title (initially implemented as part of https://github.com/kids-first/kf-ui-data-tracker/pull/485). Keeping it as a warning that can be clicked through would be fine, but there might be some thought to this still being confusing at the moment.

## Persona (link)

All users of the data tracker

## Motivation/Goal

To not prematurely cause blockers of data flow until more usage patterns are observed. 

## Supporting Evidence (qual or quant)

While generally we want to support good data practices, but we need to balance this with what is _reasonable_ and reducing friction/barriers to providing data to the DRC. Also the initial usability testing really focused on the initial upload of documents, not how things operate over time. We're running into this limit with existing studies that have reasonably named documents that are still blocked as "invalid". We should not block any file upload at this time, and then periodically review the documents/communications with investigators see how much of an issue this is over the next year.

### PR DESCRIPTION
**Pull request by XuTheBunny**
## Feature or Improvement

- **Allow everyone to upload/edit file**
- **Hide document title validation hints**
- Raise up document title similarity checking to 90%
- Reword document title similarity to file name and extensions check
- Fix document name validation step checking for similar files
- Fix similar file list unique key error

## UI changes
New document page: `/study/SD_********/documents/new-document`
**Before:**
Screen Shot 2019-11-11 at 2 34 48 PM
**After:**
Screen Shot 2019-11-22 at 10 24 37 AM
Screen Shot 2019-11-22 at 10 24 29 AM
Screen Shot 2019-11-22 at 10 25 00 AM
File edit page:
Screen Shot 2019-11-22 at 10 23 52 AM
Screen Shot 2019-11-22 at 10 23 44 AM

## Browsers Tested

| Browser             | 1024px | 768px | 480px | 320px |
| ------------------- | :----: | ----: | ----: | ----: |
| Chrome (77)  | ✅ | ✅ | ✅ | ✅ |
| Firefox (69) | ✅ | ✅ | ✅ | ✅ |
| Safari (12)  | ✅ | ✅ | ✅ | ✅ |
| IE (11)      |  ✖️   |   ✖️     |  ✖️      |    ✖️    |

Closes #520
Closes #521
Closes #529 
Closes #535

### CODE REVIEW

File: src/documents/forms/EditDocumentForm.js [hunk 1]
```diff
@@ -49,10 +50,29 @@ const EditDocumentForm = React.forwardRef(
...
+              }
+            });
+            return errors;
+          }}
           onSubmit={values => {
-            setUploading(true);
-            handleSubmit(...Object.values(values));
+            if (
+              !(
+                !isAdmin &&
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: doesn't this block non-admin users from updating file names?

Comment (XuTheBunny) [reply src/documents/forms/EditDocumentForm.js]: in this case, for the regular user, file name has to be valid before saving, for admin user, they can save the file name even when it's not valid

File: src/documents/forms/EditDocumentForm.js [hunk 2]
```diff
@@ -66,12 +86,12 @@ const EditDocumentForm = React.forwardRef(
           }) => (
             <>
               {showFieldHints &&
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: these conditionals are getting a little long (my fault) can we see if there's a better way to maybe pluck the values from objects and do the checks that way?

File: src/documents/forms/EditDocumentForm.js [hunk 3]
```diff
@@ -141,12 +161,11 @@ const EditDocumentForm = React.forwardRef(
                 </Form.Field>
                 {submitButtons &&
                   submitButtons(
-                    Object.values(values).every(x =>
-                      Boolean(x !== undefined),
-                    ) ||
-                      Object.values(errors.file_name || {}).some(
-                        x => x != null,
-                      ),
+                    Object.keys(errors).length > 0 ||
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: same here with the conditional length, maybe we can abstract these up to make them more resuable and readable (again my fault for making them daft to start with )

File: src/documents/forms/DocumentTitleValidationIndicators.js [hunk 4]
```diff
@@ -38,21 +38,29 @@ const DocumentTitleValidationIndicators = ({errors}) => {
...
         <Icon
           name={
-            (errors.file_name && errors.file_name.file_ext) ||
-            (errors.file_name && errors.file_name.upload_similarity)
+            errors.file_name && errors.file_name.upload_similarity
               ? 'x'
               : 'check'
           }
           color={
-            (errors.file_name && errors.file_name.file_ext) ||
```
Comment (bdolly) [inline src/documents/forms/DocumentTitleValidationIndicators.js]: what are we removing the file extension check here?

File: src/documents/utilities.js [hunk 5]
```diff
@@ -122,7 +122,9 @@ export const defaultSort = (a, b) => {
 };
 
 // sort list of file nodes by string similarity to file name
-export const sortFilesBySimilarity = (file, fileList, threshold = 0.3) => {
+export const sortFilesBySimilarity = (file, fileList, threshold = 0.9) => {
```
Comment (bdolly) [inline src/documents/utilities.js]: this assignment should use the global constant `STUDY_DOCS_SIMILARITY_THRESHOLD `, if not the constant isn't used

File: src/documents/forms/DocumentTitleValidationIndicators.js (hunk 4 above)
Comment (XuTheBunny) [reply src/documents/forms/DocumentTitleValidationIndicators.js]: I moved the extension check to line 54 - line 63

File: src/documents/utilities.js (hunk 5 above)
Comment (XuTheBunny) [reply src/documents/utilities.js]: We are using the global constants, I have updated their values. And here just adjusting the default threshold value in case we may want to use it in the future.

File: src/documents/forms/DocumentTitleValidationIndicators.js [hunk 6]
```diff
@@ -38,21 +38,29 @@ const DocumentTitleValidationIndicators = ({errors}) => {
...
         context.
       </List.Item>
+      <List.Item>
+        <Icon
+          name={errors.file_name && errors.file_name.file_ext ? 'x' : 'check'}
+          color={
+            errors.file_name && errors.file_name.file_ext ? 'red' : 'black'
+          }
+        />
+        Avoid using file extensions, the file name and its extension are already
```
Comment (bdolly) [inline src/documents/forms/DocumentTitleValidationIndicators.js]: I think we could combine this with the `   Name your document different than the uploaded file ..` maybe just need some better wording 

@allisonheath thoughts?

File: src/documents/forms/EditDocumentForm.js [hunk 7]
```diff
@@ -49,7 +50,16 @@ const EditDocumentForm = React.forwardRef(
             file_desc: fileDescription,
             file_status: versionStatus,
           }}
-          validate={vals => validate(vals, fileNode, studyFiles)}
+          validate={vals => {
+            setTitleError(validate(vals, fileNode, studyFiles));
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: 🙌 niice

File: src/documents/forms/EditDocumentForm.js [hunk 8]
```diff
@@ -49,7 +50,16 @@ const EditDocumentForm = React.forwardRef(
...
+            let errors = {};
+            ['file_name', 'file_type', 'file_desc'].forEach(function(field) {
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: would `Object.keys(vals)`work here ?

Comment (XuTheBunny) [reply src/documents/forms/EditDocumentForm.js]: No, because we don't want to have `file_status` here since that's only for editing existing file.

File: src/documents/forms/EditDocumentForm.js [hunk 9]
```diff
@@ -49,7 +50,17 @@ const EditDocumentForm = React.forwardRef(
...
+              if (!vals[field]) {
+                errors[field] = 'Required';
+              }
+            });
+            console.log(titleError);
```
Comment (dankolbman) [inline src/documents/forms/EditDocumentForm.js]: 🔥 Probably don't need this

**Comment by allisonheath** [comment]
How about:

"We suggest using a descriptive title without dates or adjectives such as "new", "updated", "final", etc."

**Comment by allisonheath** [comment]
@XuTheBunny 

For this release let's go with:
```
Tell us about your document
Help us process and harmonize your study faster by categorizing and describing the document you are about to upload. If you have any questions, please contact us at support@kidsfirstdrc.org.

Biospecimen Manifest
Tabular files (e.g. CSV, TSV, Excel) containing biospecimen identifiers and metadata (e.g. tissue type, composition) provided to sequencing centers as well as consent type.  

Sequencing Manifest
Tabular files (e.g. CSV, TSV, Excel) containing the biospecimen identifiers and the associated genomic data files. Typically provided by the sequencing center.  

Clinical/Phenotypic Data
Structured files with data linked to the biospecimen identifiers provided in the shipping manifest(s). Exports from data management applications, such as REDCap, are the fastest to process, but we will work with you on most formats. 

Other
Any useful documents, such as study background information, data dictionaries, etc., that does not clearly fit in the other categories. 
```

Note the change from Shipping Manifest -> Biospecimen Manifest.

We can update them in future releases if need be.

File: src/documents/views/NewDocumentView.js [hunk 10]
```diff
@@ -91,7 +91,7 @@ const NewDocumentView = ({match, history, location}) => {
             fileNode={location.state.file}
             handleSubmit={handleSubmit}
             history={history}
-            showFieldHints={true}
+            showFieldHints={false}
```
Comment (bdolly) [inline src/documents/views/NewDocumentView.js]: we still want to show the `"Please provide a descriptive title without dates or adjectives such as "new", "updated", "final", etc."` message as well as the `EditExistingDocs` notification, setting this to false blocks both of these

File: src/documents/forms/DocumentTitleValidationIndicators.js [hunk 11]
```diff
@@ -31,8 +31,8 @@ const DocumentTitleValidationIndicators = ({errors}) => {
             errors.file_name && errors.file_name.blacklisted ? 'teal' : 'black'
```
Comment (bdolly) [inline src/documents/forms/DocumentTitleValidationIndicators.js]: I think the consensus was to remove these indicators and instead use a field description on the Document Title field as Allison specified

File: src/documents/forms/EditDocumentForm.js [hunk 12]
```diff
@@ -66,12 +76,13 @@ const EditDocumentForm = React.forwardRef(
           }) => (
             <>
               {showFieldHints &&
-                errors.file_name &&
-                (errors.file_name.existing_similarity ||
-                  errors.file_name.upload_similarity) && (
+                titleError.file_name &&
+                (titleError.file_name.existing_similarity ||
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: would it make sense to do 
```js
Object.values(titleError.file_name).some(x => {<check_for_truthy_values>})
```

File: src/documents/forms/EditDocumentForm.js [hunk 13]
```diff
@@ -80,19 +91,25 @@ const EditDocumentForm = React.forwardRef(
                 <Form.Field required>
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: could these be converted to use the `/forms/FormField` component to start to standardize inputs across the application?

File: src/documents/forms/EditDocumentForm.js [hunk 14]
```diff
@@ -80,19 +91,25 @@ const EditDocumentForm = React.forwardRef(
...
                   />
-                  {Object.values(errors.file_name || {}).some(
-                    x => x != null,
-                  ) && <DocumentTitleValidationIndicators errors={errors} />}
+                  {showFieldHints &&
+                    Object.values(titleError.file_name || {}).some(
+                      x => x != null,
+                    ) && (
+                      <DocumentTitleValidationIndicators errors={titleError} />
+                    )}
```
Comment (bdolly) [inline src/documents/forms/EditDocumentForm.js]: 🔥

File: src/documents/forms/__tests__/EditDocumentFormValidation.test.js [hunk 15]
```diff
@@ -76,242 +76,14 @@ it('blocks submission for invalid Document Name input', async () => {
     });
```
Comment (bdolly) [inline src/documents/forms/__tests__/EditDocumentFormValidation.test.js]:
```
it('blocks submission for invalid Document Name input', async () => {
```
The wording could use updated to reflect that this does not block submission. 

We also need to add another test that the exact matching works.

File: src/documents/modals/UploadWizard/UploadSteps/VersionSummaryStep.js [hunk 16]
```diff
@@ -39,7 +39,7 @@ const VersionSummaryStep = ({fileToUpdate, file, setDescription}) => {
           changed in this version
         </h5>
         <Form>
-          <Form.Field required focus>
```
Comment (bdolly) [inline src/documents/modals/UploadWizard/UploadSteps/VersionSummaryStep.js]: 📓 we need to make a PR in the future to make sure the `focus` and `tabindex` works correctly for forms

File: src/documents/views/__tests__/NewDocumentView.test.js [hunk 17]
```diff
@@ -0,0 +1,132 @@
...
+          location={{state: {file: file}}}
+          history={historyMock}
+        />
+      </MemoryRouter>
+    </MockedProvider>,
+  );
+
+  await wait();
+
+  expect(tree.container).toMatchSnapshot();
```
Comment (bdolly) [inline src/documents/views/__tests__/NewDocumentView.test.js]: why take snapshots if we're not asserting that they should look a particular way?

Comment (XuTheBunny) [reply src/documents/views/__tests__/NewDocumentView.test.js]: This one is the look when a file is just uploaded, user hasn't type anything in the file name yet. The next snapshot test is user inputing. This will be different comparing to the snapshot at line 98, no warning when the fields haven't been touched vs. show warning when the name and description are touched but input is empty.

File: src/documents/forms/__tests__/EditDocumentFormValidation.test.js (hunk 15 above)
Comment (XuTheBunny) [reply src/documents/forms/__tests__/EditDocumentFormValidation.test.js]: Similar match and exact match are tested in `rc/documents/views/__tests__/NewDocumentView.test.js` line 44 - line 63.
