### PR TITLE
💄 Refactor UI margins and filter condition

### LINKED ISSUE #1151: Add ability to filter with "not" condition
**Sender**: chrisfriedman@d3b.center
**Comment**: I want to be able to see what users have no assigned studies or organization or role
[Open #165 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/165)

<a href='https://usersnappublic.s3.amazonaws.com/2021-09-13/14-37/9b2542dc-7c56-4ecd-b4ea-e3194d6ff2aa.png'>⚠️ - add ability to filter with "not" condition</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-09-13/14-37/9b2542dc-7c56-4ecd-b4ea-e3194d6ff2aa.png'>Download original image</a>

**Browser**: Firefox 92 (Macintosh)
**Referer**: [https://data-tracker.kidsfirstdrc.org/users](https://data-tracker.kidsfirstdrc.org/users)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 792

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

### PR DESCRIPTION
**Pull request by XuTheBunny**
💄 Fix release table footer length
Screen Shot 2021-12-06 at 10 01 56 PM
 
💄 Make release date inline on study release tab
Screen Shot 2021-12-06 at 9 59 58 PM
 
💄 Add margins to admin events filter dropdown
Screen Shot 2021-12-06 at 10 00 46 PM
 
✨ Add NOT condition on admin user list filter
Screen Shot 2021-12-08 at 9 15 18 PM
Closes #1151

### CODE REVIEW

File: src/admin/views/UsersView.js [hunk 1]
```diff
@@ -143,6 +155,12 @@ const UsersView = () => {
         <Form widths="equal">
           <Form.Group inline>
             <span className="pr-5">Filter by:</span>
+            <Checkbox
```
Comment (znatty22) [inline src/admin/views/UsersView.js:158]: I wonder if we should display something that explains what this filter does on hover? Like something that says  when checked this shows users that are not in the selected org OR in the selected group. Bc its not clear if this operation is a NOT org or NOT group or if its doing NOT ( org and group )

**Review by znatty22 — APPROVED** [review]
👍
