### PR TITLE
✨ Add document version preview page

### LINKED ISSUE #789: Document preview unfriendly to common binary formats like XLSX
## Relevant View or Screen

https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_0TYVY1TW/documents/SF_5BRK3GAZ

## Steps To Reproduce

Click Preview File

Screen Shot 2020-07-14 at 1 17 32 PM

## Expected Behavior

Certain binary formats like XLSX are very common in our data. It would be nice if those could be detected and interpreted.

### LINKED ISSUE #826: Move preview file button to document actions
[Open #43 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/43)
**Notes**:
 - (1) Preview button is awkwardly placed at bottom of page.
 - (2) Most document actions are listed here.

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/20-15/a5aacc07-15fe-47eb-8a64-e0efe2b16c82.png'>⚠️ - Move preview file button to document actions</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/20-15/a5aacc07-15fe-47eb-8a64-e0efe2b16c82.png'>Download original image</a>

**Browser**: Firefox 79 (Ubuntu)
**Referer**: [https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents/SF_RSKQ7YTE](https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents/SF_RSKQ7YTE)
**Screen size**: 3840 x 2160 **Browser size**: 1912 x 2071

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

### LINKED ISSUE #827: Open document previews in new tab
## Feature Justification

Opening a preview in a new tab will allow a user to browse through multiple documents and pop open previews for multiple documents of interest for comparison.

## Proposed Change or Addition

The 'Preview' button should open a file in a new tab.
The file preview should be full page 
The file preview page should have basic document info like version id and file name in a header.

### LINKED ISSUE #828: Versions cannot be previewed
[Open #44 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/44)
**Notes**:
 - (1) Past versions cannot be previewed in the Data Tracker and must be downloaded.
 - (2) Preview File only works for the latest version.

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/20-22/4b644df2-5bd1-4308-9b59-cb02aadf586e.png'>⚠️ - Versions cannot be previewed</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/20-22/4b644df2-5bd1-4308-9b59-cb02aadf586e.png'>Download original image</a>

**Browser**: Firefox 79 (Ubuntu)
**Referer**: [https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents/SF_RSKQ7YTE](https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents/SF_RSKQ7YTE)
**Screen size**: 3840 x 2160 **Browser size**: 1912 x 2071

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

### LINKED ISSUE #829: Preview document from list
**Comment**: The latest version of a document should be previewable from the document list.
[Open #45 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/45)
**Notes**:
 - (1) Actions do not contain file preview.

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/20-26/37ab1a81-af95-46e1-b27a-3ca671d8d6c7.png'>⚠️ - Preview document from list</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-05/20-26/37ab1a81-af95-46e1-b27a-3ca671d8d6c7.png'>Download original image</a>

**Browser**: Firefox 79 (Ubuntu)
**Referer**: [https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents](https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents)
**Screen size**: 3840 x 2160 **Browser size**: 1912 x 2071

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

### PR DESCRIPTION
**Pull request by XuTheBunny**
Add document preview page for specific version.
image

- Document preview page can be opened from file list, file list batch action, file detail, and file detail version list.
- Document preview page is always opened in a new browser tab.
- Study header are hidden to give full space for preview table, but user can click on the file title on header to go to file detail page.
- The table section can be expanded to full width by clicking on the expand button on top right.
- Document title and file name are shown with uploaded time on hover.
- File analysis status are displayed (number of rows and columns) if available.
- Label on the right indicates if the current preview is the latest version of the document. If not, you can click on the preview latest version button to see it.
- For the table has more than 100 rows, the first 100 rows will be displayed with the show all rows button.
- Table content can be filtered on each column.
- Warning message will be displayed if having any error getting or parsing the file.

Closes #789
Closes #826
Closes #827
Closes #828 
Closes #829

### CODE REVIEW

File: src/documents/views/VersionPreviewView.js [hunk 1]
```diff
@@ -0,0 +1,285 @@
...
+import {LogOnMount} from '@amplitude/react-amplitude';
+import {HotTable} from '@handsontable/react';
+import 'handsontable/dist/handsontable.full.css';
+
+const VersionPreviewView = ({match}) => {
+  const [fullWidth, setFullWidth] = useState(false);
+  const [displayLength, setDisplayLength] = useState(0);
+  const [loading, setLoading] = useState(false);
+  const [data, setData] = useState([]);
+  const [errors, setErrors] = useState([]);
```
Comment (dankolbman) [inline src/documents/views/VersionPreviewView.js:30]: Instead of `useState` for the data, loading, and errors, you should be able to use the hooks directly to provide that state from Apollo:
```
const {data: fileData, loading: fileLoading, error: fileError} = useQuery(GET_FILE_BY_ID, {
  variables: {kfId: match.params.fileId},
});
```

I think that using the additional state hook may possibly double the number of renders because there's twice as many state variables.

File: src/documents/views/VersionPreviewView.js [hunk 2]
```diff
@@ -0,0 +1,285 @@
...
+    file &&
+    file.versions.edges.find(v => v.node.kfId === match.params.versionId).node;
+  const latestVersionId = file && fileSortedVersions(file)[0].node.kfId;
+  const downloadURL = version && version.downloadUrl;
+
+  const getData = async limiteLength => {
+    setLoading(true);
+
+    if (version.fileName.endsWith('csv') || version.fileName.endsWith('tsv')) {
+      const resp = await fetch(downloadURL, {
```
Comment (dankolbman) [inline src/documents/views/VersionPreviewView.js:46]: You seem to repeat this twice for csv,tsv and xlsx,xls. Maybe just do it once and handle the differences elsewhere?

File: src/documents/views/VersionPreviewView.js [hunk 3]
```diff
@@ -0,0 +1,285 @@
...
+      })
+        .then(function(res) {
+          if (!res.ok) throw new Error('Failed to fetch the document');
+          return res;
+        })
+        .catch(function(err) {
+          setErrors(err.message);
+          setLoading(false);
+        });
+      if (resp) {
```
Comment (dankolbman) [inline src/documents/views/VersionPreviewView.js:59]: here is where you can fork for csv/tsv or xlsx/xls.

File: src/documents/components/FileDetail/FileDetail.js [hunk 4]
```diff
@@ -43,6 +41,30 @@ const ActionButtons = ({
...
+        inverted
+        trigger={
+          <Button
+            fluid
+            className="mb-15"
+            icon="eye"
+            primary
+            size="mini"
+            labelPosition="left"
+            onClick={e => {
```
Comment (dankolbman) [inline src/documents/components/FileDetail/FileDetail.js:56]: Could you add an Amplitude event here?

File: src/documents/components/FileActionButtons/FileActionButtons.js [hunk 5]
```diff
@@ -21,14 +21,34 @@ const FileActionButtons = ({
...
+      <Popup
+        inverted
+        position="top left"
+        content="Preview latest version"
+        trigger={
+          <Button
+            basic
+            compact
+            icon="eye"
+            onClick={e => {
```
Comment (dankolbman) [inline src/documents/components/FileActionButtons/FileActionButtons.js:40]: Could you add an Amplitude event here?

File: src/documents/components/ListFilterBar/BatchActions.js [hunk 6]
```diff
@@ -26,21 +26,56 @@ const BatchActions = ({
...
+        <Button
+          className="h-38"
+          compact
+          basic
+          primary
+          size="large"
+          icon="eye"
+          data-testid="batch-preview"
+          disabled={disabled}
+          onClick={e => {
```
Comment (dankolbman) [inline src/documents/components/ListFilterBar/BatchActions.js:43]: Could you add an Amplitude event here?

File: src/documents/components/VersionList/VersionItem.js [hunk 7]
```diff
@@ -70,6 +70,29 @@ const VersionItem = ({
...
+          inverted
+          position="top center"
+          content="Preview this Version"
+          trigger={
+            <Label
+              basic
+              size="mini"
+              as={Button}
+              onClick={e => {
+                e.stopPropagation();
```
Comment (dankolbman) [inline src/documents/components/VersionList/VersionItem.js:83]: Could you add an Amplitude event here?
