### PR TITLE
✨ Add batch download and delete document feature

### LINKED ISSUE #124: Add delete selected operation on file list
A delete button at the head of the file list should allow the user to delete selected files in the list.

### LINKED ISSUE #568: file list sort by ascending/descending toggle needs double click
## URL

https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_NY4M7ED4/documents

ascend:descend button

## Steps To Reproduce

When hitting the ascending order/ descending order button in the document tab, it requires two clicks to change the order of files.

## Expected Behavior

This should take one click.

### LINKED ISSUE #619: Download multiple files at a time
## Requirements

A checkbox should be included on the documents list for a study that will enable a bulk download button. The initial implementation should simply spawn download dialogs for each file, although a more sophisticated file compressing mechanism may later be developed.

## Motivation/Goal

Users often want to download many files from a study at a time.

### PR DESCRIPTION
**Pull request by XuTheBunny**
## Feature or Improvement

- Allow to select one/multiple/all files from study file list
- Allow batch operation: file download and file deletion (ADMIN only)

## UI changes

**[Study Documents Page](https://deploy-preview-626--kf-ui-data-tracker.netlify.com/study/SD_ME0WME0W/documents):**
**Before:**
Screen Shot 2020-03-19 at 8 23 57 PM
**After:**
Screen Shot 2020-03-19 at 8 23 42 PM
Screen Shot 2020-03-19 at 8 23 36 PM

## Browsers Tested

| Browser             | 1024px | 768px | 480px | 320px |
| ------------------- | :----: | ----: | ----: | ----: |
| Chrome (_version_)  |   ✅   |       |       |       |
| Firefox (_version_) |        |       |       |       |
| Safari (_version_)  |        |       |       |       |
| IE (_version_)      |        |       |       |       |

Closes #123 
Closes #124
Closes #619
Closes #568

### CODE REVIEW

File: src/documents/components/ListFilterBar/ListFilterBar.js [hunk 1]
```diff
@@ -88,95 +103,319 @@ const ListFilterBar = ({fileList, filteredList}) => {
...
-          value={searchString}
-        />
-        {showFilter && (
-          <Segment>
-            <p className="mb-5">
-              <Icon name="filter" />
-              Filter by:
-            </p>
-            <Dropdown
+      {selection.length > 0 ? (
```
Comment (dankolbman) [inline src/documents/components/ListFilterBar/ListFilterBar.js]: Would it be better to make the two states their own components within the filter bar?

File: src/documents/views/StudyFilesListView.js [hunk 2]
```diff
@@ -42,6 +45,35 @@ const StudyListSkeleton = () => (
...
+  const sortFuncs = {
+    createDate: createDateSort,
+    modifyDate: modifiedDateSort,
+    default: defaultSort,
+  };
+  var sortedList = fileList.sort(
+    sortFuncs[filters.sortMethod] || sortFuncs.default,
+  );
+  sortedList =
+    filters.sortDirection === 'ascending' ? sortedList : sortedList.reverse();
```
Comment (dankolbman) [inline src/documents/views/StudyFilesListView.js]: I think this is why it takes two clicks to sort. It will only reverse when the value is `descending`.
Maybe move the direction out of the filter function and do it like this:
```
  const filteredFiles =                                                             
    filters.sortDirection === 'ascending'                                                                                                                                                                                                     
      ? filterFiles(files, filters)                                                 
      : filterFiles(files, filters).reverse();  
```

File: src/documents/components/ListFilterBar/BatchActionBar.js [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+const BatchActionBar = ({
+  fileList,
+  studyId,
+  selection,
+  setSelection,
+  downloadFileMutation,
+  deleteFile,
+}) => (
+  <Segment className="noHorizontalPadding mt-0" clearing basic textAlign="left">
+    <div className="small-inline">
```
[the remark this answers is not in the document]
Comment (XuTheBunny) [reply src/documents/components/ListFilterBar/BatchActionBar.js]: `<span>` cannot have the padding from top
